server:
  port: 5590

jwt:
  secret: aziz-secret-key
  lifetime: 30m

spring:
  application:
    name: task-management
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/task_db
    username: azizdev
    password: pass_sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  mvc:
    log-request-details: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_NAME}
    password: ${EMAIL_APP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:${server.port}

logging:
  level:
    org.springframework.web: debug
    org.hibernate.SQL: INFO
    org:
      springframework:
        security: DEBUG